# Server configuration change web server port
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: admin
    password: admin
  jpa:
    hibernate:
      # drop table when restart the server
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  # Disable or Enable web server
  main:
    web-application-type: servlet